'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Branch
    Public Property BranchID As String
    Public Property BranchName As String
    Public Property Status As String
    Public Property UserId As String

    Public Overridable Property tblUser As tblUser
    Public Overridable Property Side As ICollection(Of Side) = New HashSet(Of Side)

End Class
