'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Position
    Public Property PositionID As String
    Public Property PositionName As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property Status As String
    Public Property DepartmentID As String

    Public Overridable Property Department As Department

End Class
