'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Referal_Doc
    Public Property ReflID As String
    Public Property Firstname As String
    Public Property Lastname As String
    Public Property Department As String
    Public Property [Date] As String
    Public Property Refdate As String
    Public Property Source As String
    Public Property Remark As String
    Public Property Company As String
    Public Property Person As String
    Public Property Tel As String
    Public Property Email As String
    Public Property Line As String
    Public Property Detail As String
    Public Property Servicetype As String
    Public Property Typeremark As String
    Public Property Commodity As String
    Public Property Weight As String
    Public Property Volume As String
    Public Property Dimension As String
    Public Property Origin As String
    Public Property Destination As String
    Public Property Special As String

End Class
