'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAccessListDetail
    Public Property AccessNo As String
    Public Property ItemNo As String
    Public Property TypeOfDevice As String
    Public Property NameOfDevice As String
    Public Property Price As Nullable(Of Double)
    Public Property OrderNo As String
    Public Property WarrantyValue As Nullable(Of Double)
    Public Property WarrantyUnit As String
    Public Property StartWarranty As Nullable(Of Date)
    Public Property EndWarranty As Nullable(Of Date)
    Public Property PlaceOfWarranty As String
    Public Property SupplierCode As String
    Public Property SupplierName As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property ModifyDate As Nullable(Of Date)
    Public Property ModifyName As String

End Class
