'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAccessList
    Public Property AccessNo As String
    Public Property AccessName As String
    Public Property RecordDate As Nullable(Of Date)
    Public Property TypeofAccess As String
    Public Property OrderNo As String
    Public Property OrderDate As Nullable(Of Date)
    Public Property ValueOfAccess As Nullable(Of Double)
    Public Property WarrantyValue As String
    Public Property WarrantyUnit As String
    Public Property StartWarranty As Nullable(Of Date)
    Public Property EndWarranty As Nullable(Of Date)
    Public Property PlaceOfWarranty As String
    Public Property SupplierCode As String
    Public Property SupplierName As String
    Public Property Remark As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property ModifyDate As Nullable(Of Date)
    Public Property ModifyBy As String
    Public Property StatusOnStock As String
    Public Property SN As String
    Public Property Branch As String
    Public Property Department As String
    Public Property Owner As String
    Public Property AccessAccount As String
    Public Property ReceiveDate As Nullable(Of Date)

End Class
