'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAbsent
    Public Property IDAbsent As Integer
    Public Property CodeID As String
    Public Property firstname As String
    Public Property SentDate As Date
    Public Property SentTo As String
    Public Property SentTo1 As String
    Public Property SentTo2 As String
    Public Property Department As String
    Public Property Address As String
    Public Property Sections As String
    Public Property numday As Nullable(Of Integer)
    Public Property numhr As Nullable(Of Integer)
    Public Property nummin As Nullable(Of Integer)
    Public Property TypeAbsent As String
    Public Property formatAbsent As String
    Public Property approvedate As Nullable(Of Date)
    Public Property approve1date As Nullable(Of Date)
    Public Property why As String
    Public Property SAbDate As Nullable(Of Date)
    Public Property SAbTime As String
    Public Property EAbDate As Nullable(Of Date)
    Public Property EAbTime As String
    Public Property Country As String
    Public Property CountryName As String
    Public Property BookAbsent As String
    Public Property Office As String
    Public Property NameOff As String
    Public Property Why2 As String
    Public Property DocAbsent As String
    Public Property DocAbsent2 As String
    Public Property DocAbsent3 As String
    Public Property fileupload As String
    Public Property fileupload2 As String
    Public Property fileupload3 As String
    Public Property Status As String
    Public Property DataStatus As String
    Public Property SDay As String
    Public Property SMonth As String
    Public Property SYear As String
    Public Property MailOff As String
    Public Property statusOff As String
    Public Property PeriodYear As String
    Public Property ansTime As String
    Public Property FileText As String
    Public Property comment As String
    Public Property MailCC As String
    Public Property Docsta As String

End Class
