'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblBookingMessenger
    Public Property RecNo As Decimal
    Public Property BookingDate As Nullable(Of Date)
    Public Property BookingTime As String
    Public Property CusTel As String
    Public Property ContactPerson As String
    Public Property CustomerName As String
    Public Property Location As String
    Public Property JobType1 As String
    Public Property JobType2 As String
    Public Property JobType3 As String
    Public Property JobDesc As String
    Public Property ReceiveComback As String
    Public Property BookingBy As String
    Public Property Branch As String
    Public Property Messenger As String
    Public Property Status As String
    Public Property Remark As String
    Public Property ReceiveBy As String
    Public Property StatusJob As Nullable(Of Integer)
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property JobType4 As String

End Class
