'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblItJobDoc
    Public Property ItJobDocID As String
    Public Property RequestFrom As String
    Public Property UserIP As String
    Public Property RecipientJob As String
    Public Property Position As String
    Public Property AssignJobTo As String
    Public Property CloseDate As Nullable(Of Date)
    Public Property UserTel As String
    Public Property CaseJobID As String
    Public Property JobDetail As String
    Public Property RepairDetail As String
    Public Property Comment As String
    Public Property JobStatus As String
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property Updateby As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property DivisionName As String

End Class
