'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblIDRecording
    Public Property recordingID As Integer
    Public Property recordingDate As Nullable(Of Date)
    Public Property problems As String
    Public Property reason As String
    Public Property branch As String
    Public Property recording_Time As String
    Public Property recordingTime As Nullable(Of System.TimeSpan)

End Class
