'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblMessenger
    Public Property MessDate As Date
    Public Property Name As String
    Public Property TimeOut As String
    Public Property MileOut As Nullable(Of Decimal)
    Public Property TimeIn As String
    Public Property MileIn As Nullable(Of Decimal)
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)

End Class
