'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblUsername
    Public Property UserName As String
    Public Property Password As String
    Public Property Name As String
    Public Property CustomerCode As String
    Public Property UserGroup As String
    Public Property GroupName As String
    Public Property UserStatus As String
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property EditBy As String
    Public Property EditDate As Nullable(Of Date)

End Class
