'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblUserMenu
    Public Property UserID As String
    Public Property Menu As String
    Public Property Status As String
    Public Property Read_ As Nullable(Of Integer)
    Public Property Save_ As Nullable(Of Integer)
    Public Property Edit_ As Nullable(Of Integer)
    Public Property Delete_ As Nullable(Of Integer)
    Public Property UserBy As String
    Public Property LastUpdate As Nullable(Of Date)

End Class
