'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblUserGroup
    Public Property UserGroupCode As String
    Public Property UserGroupName As String
    Public Property UserBy As String
    Public Property UpdateBy As Nullable(Of Date)

End Class
